jwt:
  secret: this+is+my+secret+token+and+need+to+contain+a+lot+of+chars$

server:
  port: 8081
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportal
    password: 12345678
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#  mvc:
#    throw-exception-if-no-handler-found: true
#    resources:
#      add-mappings: false



#        #to enable witheLable error page
#  mvc:
#    throw-exception-if-no-handler-found: true #if cant find any handler just throw the exception
#  resources:
#    add-mappings: false


